import type { AppForgeConfig, ProjectDetection, Target } from "../types.js";

type View = "dashboard" | "project" | "targets" | "builds" | "development" | "config" | "doctor" | "settings";
interface ProjectState { projectPath: string; detection: ProjectDetection; config?: AppForgeConfig; configError?: string; }
interface HistoryRecord { id: string; target: Target | "all"; status: "success" | "failure"; timestamp: string; durationMs: number; outputPaths: string[]; error?: string; }
interface DevState { running: boolean; command?: string; cwd?: string; url?: string; stdout: string; stderr: string; error?: string; exitCode?: number; }
interface ApiState { view: View; project?: ProjectState; message?: string; error?: string; busy: boolean; lastBuild?: unknown; history: HistoryRecord[]; doctor?: string[]; dev?: DevState; }

const views: Array<{ id: View; label: string; icon: string }> = [
  { id: "dashboard", label: "Dashboard", icon: "⌂" },
  { id: "project", label: "Project", icon: "▣" },
  { id: "targets", label: "Targets", icon: "◇" },
  { id: "builds", label: "Builds", icon: "↗" },
  { id: "development", label: "Development", icon: "▷" },
  { id: "config", label: "Configuration", icon: "{}" },
  { id: "doctor", label: "Doctor", icon: "✚" },
];

const state: ApiState = { view: "dashboard", busy: false, history: [] };

export function renderApp(root: HTMLDivElement): void {
  const draw = () => { root.innerHTML = shell(); bind(draw); };
  draw();
}

function shell(): string {
  const active = views.find((view) => view.id === state.view) ?? views[0];
  return `<div class="app-shell">
    <aside class="sidebar">
      <div class="brand"><span class="brand-mark">AF</span><span>AppForge</span></div>
      <div class="workspace"><span class="eyebrow">WORKSPACE</span><strong>${state.project ? escapeHtml(state.project.projectPath.split(/[\\/]/).pop() || "Project") : "No project connected"}</strong><span class="workspace-state"><i class="dot ${state.project ? "green" : "gray"}"></i>${state.project ? "Connected" : "Awaiting connection"}</span></div>
      <nav aria-label="Main navigation">${views.map((view) => `<button class="nav-item ${view.id === state.view ? "active" : ""}" data-view="${view.id}"><span class="nav-icon">${view.icon}</span>${view.label}</button>`).join("")}</nav>
      <div class="sidebar-bottom"><button class="nav-item ${state.view === "settings" ? "active" : ""}" data-view="settings"><span class="nav-icon">⚙</span>Settings</button><div class="version">APPFORGE <span>v0.1.0</span></div></div>
    </aside>
    <main class="main"><header class="topbar"><div><span class="breadcrumb">${active.label.toUpperCase()}</span><span class="slash">/</span><span class="muted">Local workspace</span></div><div class="top-actions"><span class="status-chip"><i class="dot ${state.project ? "green" : "gray"}"></i>${state.project ? "Ready" : "Not connected"}</span><button class="icon-button" title="Settings" data-view="settings">⚙</button></div></header>${content(active.label)}</main>
  </div>`;
}

function content(label: string): string {
  if (state.view === "dashboard") return dashboard();
  if (state.view === "project") return project();
  if (state.view === "targets") return targets();
  if (state.view === "builds") return builds();
  if (state.view === "development") return development();
  if (state.view === "config") return config();
  if (state.view === "doctor") return doctor();
  return page(label, "Workspace preferences will appear here once they control a real AppForge setting.");
}

function dashboard(): string {
  const detection = state.project?.detection;
  const targets = state.project?.config?.targets ?? [];
  return `<section class="page"><div class="page-heading"><div><span class="eyebrow">OVERVIEW</span><h1>Project control center</h1><p>Manage your web project and its native targets from one place.</p></div><button class="primary" data-connect>${state.busy ? "Working..." : state.project ? "Reconnect project" : "Connect project"}<span>→</span></button></div>${feedback()}${state.project ? `<div class="notice success"><i class="dot green"></i><div><strong>Project connected</strong><span>${escapeHtml(detection?.framework ?? "unknown")} detected with ${escapeHtml(detection?.packageManager ?? "unknown")}.</span></div></div>` : emptyState()}<div class="section-label">CURRENT STATUS</div><div class="metric-grid"><article class="metric"><span class="eyebrow">PROJECT</span><strong>${escapeHtml(state.project?.projectPath ?? "—")}</strong><small>Connected project path</small></article><article class="metric"><span class="eyebrow">FRAMEWORK</span><strong>${escapeHtml(detection?.framework ?? "—")}</strong><small>${escapeHtml(detection?.evidence.join(", ") ?? "Connect a project to detect")}</small></article><article class="metric"><span class="eyebrow">BUILD COMMAND</span><strong>${escapeHtml(state.project?.config?.web.buildCommand ?? detection?.buildCommand ?? "—")}</strong><small>${state.lastBuild ? "Last build returned from core" : "No build recorded"}</small></article><article class="metric"><span class="eyebrow">PACKAGE MANAGER</span><strong>${escapeHtml(detection?.packageManager ?? "—")}</strong><small>${state.project?.config ? "Configuration loaded" : state.project?.configError ?? "Run Init to create config"}</small></article></div><div class="section-label">TARGETS</div><div class="target-grid"><target-card title="Desktop" tech="Electron" icon="▣" target="desktop" enabled="${targets.includes("electron")}"></target-card><target-card title="Mobile" tech="Capacitor" icon="◇" target="mobile" enabled="${targets.includes("capacitor")}"></target-card></div>${state.project ? `<div class="action-row"><button class="secondary" data-action="build">Build</button><button class="secondary" data-action="doctor">Doctor</button><button class="secondary" data-action="clean">Clean</button></div>` : ""}</section>`;
}

function emptyState(): string { return `<div class="empty-state"><div class="empty-symbol">+</div><div><h2>No project connected</h2><p>Choose a local web project to inspect its framework, configure targets, and run builds.</p></div><button class="secondary" data-connect>Connect project</button></div>`; }
function feedback(): string { return state.error ? `<div class="notice error"><i class="dot red"></i><div><strong>Operation failed</strong><span>${escapeHtml(state.error)}</span></div></div>` : state.message ? `<div class="notice success"><i class="dot green"></i><div><strong>Operation complete</strong><span>${escapeHtml(state.message)}</span></div></div>` : ""; }
function project(): string { const project = state.project; return page("Project", "Detection comes from the connected project on the local AppForge server.", project ? `<div class="panel detail-grid"><strong>Path</strong><span>${escapeHtml(project.projectPath)}</span><strong>Framework</strong><span>${escapeHtml(project.detection.framework)}</span><strong>Package manager</strong><span>${escapeHtml(project.detection.packageManager)}</span><strong>Build</strong><span>${escapeHtml(project.config?.web.buildCommand ?? project.detection.buildCommand ?? "Not detected")}</span><strong>Output</strong><span>${escapeHtml(project.config?.web.outputDirectory ?? project.detection.outputDirectory ?? "Not detected")}</span></div>` : `<div class="panel empty-panel"><h2>Project details unavailable</h2><p>Connect a local project to populate detection data.</p><button class="secondary" data-connect>Connect local project</button></div>`); }
function targets(): string { const enabled = state.project?.config?.targets ?? []; return page("Targets", "Manage adapters and inspect their real prerequisite status.", `<div class="target-grid">${targetCard("Desktop", "Electron", "desktop", enabled.includes("electron"))}${targetCard("Mobile", "Capacitor", "mobile", enabled.includes("capacitor"))}</div>`); }
function builds(): string { return page("Builds", "Every entry below is persisted by the shared build pipeline.", `<div class="action-row"><button class="primary" data-build-target="all">Build all</button>${(state.project?.config?.targets ?? []).map((target) => `<button class="secondary" data-build-target="${target === "electron" ? "desktop" : "mobile"}">Build ${target}</button>`).join("")}</div>${state.history.length ? `<div class="history-list">${state.history.slice().reverse().map((item) => `<article class="panel history-item"><div><strong>${escapeHtml(item.target)}</strong><span class="muted">${escapeHtml(new Date(item.timestamp).toLocaleString())} · ${item.durationMs} ms</span></div><span class="status-chip"><i class="dot ${item.status === "success" ? "green" : "red"}"></i>${item.status}</span>${item.error ? `<pre>${escapeHtml(item.error)}</pre>` : `<small>${escapeHtml(item.outputPaths.join("\n") || "No output paths")}</small>`}</article>`).join("")}</div>` : `<div class="panel empty-panel"><h2>No build history</h2><p>Run a build to create the first real record.</p></div>`}`); }
function development(): string { const dev = state.dev; return page("Development", "Run and inspect the connected project's configured development command.", `<div class="panel dev-panel"><div class="panel-top"><div><span class="eyebrow">WEB PREVIEW</span><h2>${dev?.running ? "Development server running" : "Development server stopped"}</h2><span class="muted">${escapeHtml(dev?.command ?? "Not started")}</span></div><span class="status-chip"><i class="dot ${dev?.running ? "green" : "gray"}"></i>${dev?.running ? "Running" : "Stopped"}</span></div><div class="action-row"><button class="primary" data-dev="start">Start</button><button class="secondary" data-dev="stop">Stop</button>${dev?.url ? `<a class="secondary link-button" href="${escapeHtml(dev.url)}" target="_blank" rel="noreferrer">Open preview</a>` : ""}</div><div class="terminal"><pre>${escapeHtml(`${dev?.stdout ?? ""}${dev?.stderr ? `\n${dev.stderr}` : ""}` || "No process output yet.")}</pre></div></div>`); }
function config(): string { const value = state.project?.config; return page("Configuration", "Edit the validated appforge.config.json used by the CLI.", value ? `<form class="panel config-form" data-config-form><label>Name<input name="name" value="${escapeHtml(value.name)}" required></label><label>Web root<input name="root" value="${escapeHtml(value.web.root)}" required></label><label>Build command<input name="buildCommand" value="${escapeHtml(value.web.buildCommand)}"></label><label>Output directory<input name="outputDirectory" value="${escapeHtml(value.web.outputDirectory)}" required></label><label>Dev command<input name="devCommand" value="${escapeHtml(value.web.devCommand ?? "")}"></label><label>Dev URL<input name="devUrl" value="${escapeHtml(value.web.devUrl ?? "")}"></label><label><input type="checkbox" name="desktop" ${value.targets.includes("electron") ? "checked" : ""}> Desktop target</label><label><input type="checkbox" name="mobile" ${value.targets.includes("capacitor") ? "checked" : ""}> Mobile target</label><button class="primary">Save configuration</button></form>` : `<div class="panel empty-panel"><h2>Configuration missing</h2><p>${escapeHtml(state.project?.configError ?? "Connect a project first.")}</p></div>`); }
function doctor(): string { return page("Doctor", "Real prerequisite checks from the connected project and target adapters.", state.doctor ? `<div class="panel"><pre>${escapeHtml(state.doctor.join("\n"))}</pre></div>` : `<div class="panel empty-panel"><h2>Diagnostics not run</h2><p>Run Doctor to inspect the current environment.</p><button class="secondary" data-action="doctor">Run Doctor</button></div>`); }
function page(title: string, description: string, body = ""): string { return `<section class="page"><div class="page-heading"><div><span class="eyebrow">APPFORGE</span><h1>${title}</h1><p>${description}</p></div></div>${body}</section>`; }
function targetCard(title: string, tech: string, target: Target | "desktop" | "mobile", enabled = false): string { const uiTarget = target === "electron" ? "desktop" : target === "capacitor" ? "mobile" : target; return `<article class="target-card"><div class="target-icon">${target === "electron" || target === "desktop" ? "▣" : "◇"}</div><div class="target-copy"><span class="eyebrow">${title.toUpperCase()}</span><h3>${tech}</h3><span class="muted">${enabled ? "Configured" : state.project ? "Not configured" : "Awaiting project connection"}</span></div>${state.project ? `<button class="secondary compact" data-target-action="${enabled ? "remove" : "add"}" data-target="${uiTarget}">${enabled ? "Remove" : `Add ${title}`}</button>${enabled ? `<button class="secondary compact" data-build-target="${uiTarget}">Build</button>` : ""}` : ""}</article>`; }

function bind(draw: () => void): void {
  document.querySelectorAll<HTMLElement>("[data-view]").forEach((element) => element.addEventListener("click", () => { state.view = element.dataset.view as View; draw(); }));
  document.querySelectorAll<HTMLFormElement>("[data-connect-form]").forEach((form) => form.addEventListener("submit", (event) => { event.preventDefault(); const data = new FormData(form); void action(draw, async () => { state.project = await callApi<ProjectState>("/connect", { method: "POST", body: JSON.stringify({ projectPath: data.get("projectPath") }) }); await refresh(); return "Project connected."; }); }));
  document.querySelectorAll<HTMLElement>("[data-connect]").forEach((element) => element.addEventListener("click", () => { state.view = "dashboard"; draw(); }));
  document.querySelectorAll<HTMLElement>("[data-target-action]").forEach((element) => element.addEventListener("click", () => void action(draw, async () => { const target = element.dataset.target!; const method = element.dataset.targetAction === "remove" ? "DELETE" : "POST"; await callApi("/targets", { method, body: JSON.stringify({ target }) }); state.project = await callApi<ProjectState>("/project"); return `${target} target ${method === "DELETE" ? "removed" : "added"}.`; })));
  document.querySelectorAll<HTMLElement>("[data-build-target]").forEach((element) => element.addEventListener("click", () => void action(draw, async () => { const target = element.dataset.buildTarget; await callApi("/build", { method: "POST", body: JSON.stringify({ target: target === "all" ? undefined : target }) }); await refresh(); return "Build pipeline completed."; })));
  document.querySelectorAll<HTMLElement>("[data-dev]").forEach((element) => element.addEventListener("click", () => void action(draw, async () => { state.dev = await callApi<DevState>(`/dev/${element.dataset.dev}`, { method: "POST", body: "{}" }); return `Development server ${element.dataset.dev === "start" ? "started" : "stopped"}.`; })));
  document.querySelectorAll<HTMLFormElement>("[data-config-form]").forEach((form) => form.addEventListener("submit", (event) => { event.preventDefault(); const data = new FormData(form); void action(draw, async () => { const config = { name: data.get("name"), web: { root: data.get("root"), buildCommand: data.get("buildCommand"), outputDirectory: data.get("outputDirectory"), devCommand: data.get("devCommand"), devUrl: data.get("devUrl") }, targets: [data.get("desktop") ? "desktop" : "", data.get("mobile") ? "mobile" : ""].filter(Boolean) }; state.project = { ...state.project!, config: await callApi<AppForgeConfig>("/config", { method: "PUT", body: JSON.stringify(config) }) }; return "Configuration saved."; }); }));
  document.querySelectorAll<HTMLElement>("[data-action=doctor]").forEach((element) => element.addEventListener("click", () => void action(draw, async () => { state.doctor = (await callApi<{ statuses: string[] }>("/doctor")).statuses; return "Doctor checks refreshed."; })));
}
async function refresh(): Promise<void> { state.history = await callApi<HistoryRecord[]>("/history"); state.dev = await callApi<DevState>("/dev"); }
async function callApi<T>(endpoint: string, init?: RequestInit): Promise<T> { const response = await fetch(`/api${endpoint}`, { headers: { "content-type": "application/json" }, ...init }); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? `Request failed (${response.status})`); return body; }
async function action(draw: () => void, operation: () => Promise<string>): Promise<void> { state.busy = true; state.error = undefined; state.message = undefined; draw(); try { state.message = await operation(); } catch (error) { state.error = error instanceof Error ? error.message : String(error); } finally { state.busy = false; draw(); } }
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] ?? character); }